spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Estratégia de criação de schema (update, validate, create, create-drop)
    show-sql: true      # Exibir SQL no console
    properties:
      hibernate:
        format_sql: true  # Formatar SQL para melhor visualização

  application:
    name: mentoria  # Nome da aplicação
